name: Build and Test

env:
  # Change cache version if running into issues
  # Github forces fresh environment every 7 days or when the identifier changes
  CACHE_VERSION: 1

on:
  push:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build and test container on ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore base ubuntu environment
        id: cache-ubuntu
        uses: actions/cache@v2
        env:
          cache-name: cache-ubuntu
        with:
          path: ~/
          key: >-
            ${{ env.CACHE_VERSION}}-${{ runner.os }}-ubuntu-${{
            hashFiles('~/Dockerfile') }}
          restore-keys: |
            ${{ env.CACHE_VERSION}}-${{ runner.os }}-ubuntu
      - name: Build but not push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: mkdocs
      - name: Delete svgs if existing (in cache)
        run: |
          rm site/*drawio*svg || true
      - name: Test using update script
        run: |
          ./update.sh
      - name: Show created svg
        run: |
          test -f site/example.drawio-0.svg
